#include-once

Global $VKEY_CONVERSION[256] = [ _
'', '', '', '', '', '', '', '', 'BS', 'TAB', _
'', '', '', 'ENTER', '', '', '', '', '', 'PAUSE', _
'CAPSLOCK', '', '', '', '', '', '', 'ESC', '', '', _
'', '', 'SPACE', 'PGUP', 'PGDN', 'END', 'HOME', 'LEFT', 'UP', 'RIGHT', _
'DOWN', '', '', '', 'PRINTSCREEN', 'INS', 'DEL', '', '0', '1', _
'2', '3', '4', '5', '6', '7', '8', '9', '', '', _
'', '', '', '', '', 'A', 'B', 'C', 'D', 'E', _
'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', _
'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', _
'Z', 'LWIN', 'RWIN', 'MENU', '', '', 'NUMPAD0', 'NUMPAD1', 'NUMPAD2', 'NUMPAD3', _
'NUMPAD4', 'NUMPAD5', 'NUMPAD6', 'NUMPAD7', 'NUMPAD8', 'NUMPAD9', 'NUMPADMULT', 'NUMPADADD', '', 'NUMPADSUB', _
'NUMPADDOT', 'NUMPADDIV', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', _
'F9', 'F10', 'F11', 'F12', '', '', '', '', '', '', _
'', '', '', '', '', '', '', '', '', '', _
'', '', '', 'NUMLOCK', '', 'SCROLLLOCK', '', '', '', '', _
'', '', '', '', '', '', '', '', '', '', _
'LSHIFT', 'RSHIFT', 'LCTRL', 'RCTRL', '', '', '', '', '', '', _
'', '', '', '', '', '', '', '', '', '', _
'', '', '', '', '', '', ';', '=', ',', '-', _
'.', '/', '`', '', '', '', '', '', '', '', _
'', '', '', '', '', '', '', '', '', '', _
'', '', '', '', '', '', '', '', '', '[', _
'\', ']', "'", '', '', '', '<', '', '', '', _
'', '', '', '', '', '', '', '', '', '', _
'', '', '', '', '', '', '', '', '', '', _
'', '', '', '', '', '' ]

Func vKey($Key)
	If $Key < 0 Or $Key > 255 Then Return
	Return $VKEY_CONVERSION[$Key]
EndFunc

Func HexKey($Key)
	Local $Hex
	Switch $Key
	Case "{LMB}"
		$Hex = "01"
	Case "{RMB}"
		$Hex = "02"
	Case "{MMB}"
		$Hex = "04"
	Case "{BACKSPACE}", "{BS}"
		$Hex = "08"
	Case "{TAB}"
		$Hex = "09"
	Case "{ENTER}"
		$Hex = "0D"
	Case "{SHIFT}"
		$Hex = "10"
	Case "{CTRL}"
		$Hex = "11"
	Case "{ALT}"
		$Hex = "12"
	Case "{CAPSLOCK}"
		$Hex = "14"
	Case "{ESC}"
		$Hex = "1B"
	Case "{SPACE}"
		$Hex = "20"
	Case "{PGUP}"
		$Hex = "21"
	Case "{PGDN}"
		$Hex = "22"
	Case "{END}"
		$Hex = "23"
	Case "{HOME}"
		$Hex = "24"
	Case "{LEFT}"
		$Hex = "25"
	Case "{UP}"
		$Hex = "26"
	Case "{RIGHT}"
		$Hex = "27"
	Case "{DOWN}"
		$Hex = "28"
	Case "{INS}"
		$Hex = "2D"
	Case "{DEL}"
		$Hex = "2E"
	Case "0"
		$Hex = "30"
	Case "1"
		$Hex = "31"
	Case "2"
		$Hex = "32"
	Case "3"
		$Hex = "33"
	Case "4"
		$Hex = "34"
	Case "5"
		$Hex = "35"
	Case "6"
		$Hex = "36"
	Case "7"
		$Hex = "37"
	Case "8"
		$Hex = "38"
	Case "9"
		$Hex = "39"
	Case "A"
		$Hex = "41"
	Case "B"
		$Hex = "42"
	Case "C"
		$Hex = "43"
	Case "D"
		$Hex = "44"
	Case "E"
		$Hex = "45"
	Case "F"
		$Hex = "46"
	Case "G"
		$Hex = "47"
	Case "H"
		$Hex = "48"
	Case "I"
		$Hex = "49"
	Case "J"
		$Hex = "4A"
	Case "K"
		$Hex = "4B"
	Case "L"
		$Hex = "4C"
	Case "M"
		$Hex = "4D"
	Case "N"
		$Hex = "4E"
	Case "O"
		$Hex = "4F"
	Case "P"
		$Hex = "50"
	Case "Q"
		$Hex = "51"
	Case "R"
		$Hex = "52"
	Case "S"
		$Hex = "53"
	Case "T"
		$Hex = "54"
	Case "U"
		$Hex = "55"
	Case "V"
		$Hex = "56"
	Case "W"
		$Hex = "57"
	Case "X"
		$Hex = "58"
	Case "Y"
		$Hex = "59"
	Case "Z"
		$Hex = "5A"
	Case "{WIN}"
		$Hex = "5B"
	Case "{LWIN}"
		$Hex = "5B"
	Case "{RWIN}"
		$Hex = "5C"
	Case "{MENU}"
		$Hex = "5D"
	Case "{F1}"
		$Hex = "70"
	Case "{F2}"
		$Hex = "71"
	Case "{F3}"
		$Hex = "72"
	Case "{F4}"
		$Hex = "73"
	Case "{F5}"
		$Hex = "74"
	Case "{F6}"
		$Hex = "75"
	Case "{F7}"
		$Hex = "76"
	Case "{F8}"
		$Hex = "77"
	Case "{F9}"
		$Hex = "78"
	Case "{F10}"
		$Hex = "79"
	Case "{F11}"
		$Hex = "7A"
	Case "{F12}"
		$Hex = "7B"
	Case "{NUMLOCK}"
		$Hex = "90"
	Case "{SCROLLLOCK}"
		$Hex = "91"
	Case "{LSHIFT}"
		$Hex = "A0"
	Case "{RSHIFT}"
		$Hex = "A1"
	Case "{LCTRL}"
		$Hex = "A2"
	Case "{RCTRL}"
		$Hex = "A3"
	Case ";"
		$Hex = "BA"
	Case "="
		$Hex = "BB"
	Case ","
		$Hex = "BC"
	Case "-"
		$Hex = "BD"
	Case "."
		$Hex = "BE"
	Case "/"
		$Hex = "BF"
	Case "`"
		$Hex = "C0"
	Case "]"
		$Hex = "DB"
	Case "\"
		$Hex = "DC"
	Case "]"
		$Hex = "DD"
	EndSwitch
	Return $Hex
EndFunc
